#!/bin/bash
# How to?
#    ./run {route-folder} {packages.scripts}
#
# As an example below:
#    ./run superheros dev
#    ./run superheros-in dev
#    ./run superheros-out dev
#    ./run landing dev
#
# Others such as:
#    ./run superheros build
#    ./run superheros package
ROUTE_FOLDER=$1 $(which npm) run $2 ${@:3}
